'use strict';

const KEY='moje-remeslo-state-v2';
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const pad=n=>String(n).padStart(2,'0');
const iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const todayIso=()=>iso(new Date());
const money=n=>Number(n||0).toLocaleString('cs-CZ')+' Kč';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=p=>(p||'id')+'_'+Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const fmtDate=s=>{if(!s)return '—';const [y,m,d]=s.split('-');return `${Number(d)}. ${Number(m)}. ${y}`};
const fmtShort=s=>{if(!s)return '';const [y,m,d]=s.split('-');return `${Number(d)}.${Number(m)}.`};
const monthNames=['leden','únor','březen','duben','květen','červen','červenec','srpen','září','říjen','listopad','prosinec'];
const dayNames=['Ne','Po','Út','St','Čt','Pá','So'];

const ICONS={
  home:'<path d="M3 11l9-7 9 7"/><path d="M5 10v10h14V10"/>',
  calendar:'<rect x="3" y="5" width="18" height="16"/><path d="M8 3v4M16 3v4M3 10h18"/>',
  briefcase:'<rect x="3" y="7" width="18" height="13"/><path d="M8 7V5h8v2M3 12h18"/>',
  users:'<circle cx="9" cy="8" r="3"/><path d="M3 20c0-4 2-6 6-6s6 2 6 6M16 10c2.5 0 4 1.5 4 4v4"/>',
  file:'<path d="M6 3h9l3 3v15H6z"/><path d="M9 11h6M9 15h6"/>',
  clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
  phone:'<path d="M5 4l3-1 2 5-2 2c1.5 3 3 4.5 6 6l2-2 5 2-1 3c-.4 1.2-1.3 2-2.7 2C10 20 4 14 3 6.7 3 5.3 3.8 4.4 5 4z"/>',
  pin:'<path d="M12 21s6-5.3 6-11a6 6 0 10-12 0c0 5.7 6 11 6 11z"/><circle cx="12" cy="10" r="2"/>',
  plus:'<path d="M12 5v14M5 12h14"/>',
  search:'<circle cx="11" cy="11" r="7"/><path d="M20 20l-4-4"/>',
  archive:'<path d="M4 7h16v13H4zM3 4h18v3H3zM9 11h6"/>',
  chevron:'<path d="M9 6l6 6-6 6"/>',
  camera:'<rect x="3" y="7" width="18" height="13"/><path d="M8 7l1.5-3h5L16 7"/><circle cx="12" cy="13" r="3"/>',
  euro:'<path d="M17 7a6 6 0 100 10M4 10h10M4 14h9"/>',
  check:'<path d="M5 12l4 4L19 6"/>',
  menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',
  trash:'<path d="M4 7h16M9 7V5h6v2M7 7l1 14h8l1-14"/>',
  edit:'<path d="M12 20h9M16.5 3.5a2 2 0 013 3L7 19l-4 1 1-4z"/>',
  offer:'<path d="M5 3h11l3 3v15H5z"/><path d="M9 10h6M9 14h6M9 18h4"/>',
  person:'<circle cx="12" cy="8" r="4"/><path d="M4 21c0-5 3-7 8-7s8 2 8 7"/>',
  task:'<rect x="4" y="4" width="16" height="16"/><path d="M8 9l2 2 4-4M8 15h8"/>',
  download:'<path d="M12 3v12M7 10l5 5 5-5M5 21h14"/>',
  share:'<circle cx="18" cy="5" r="2"/><circle cx="6" cy="12" r="2"/><circle cx="18" cy="19" r="2"/><path d="M8 11l8-5M8 13l8 5"/>'
};
function icon(name,size=20){return `<svg viewBox="0 0 24 24" width="${size}" height="${size}" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${ICONS[name]||ICONS.file}</svg>`}
function hydrateIcons(){$$('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));}

function demoState(){
  const now=new Date(),t=todayIso();
  const d1=new Date(now);d1.setDate(now.getDate()+1);
  const d2=new Date(now);d2.setDate(now.getDate()+3);
  const last=new Date(now);last.setDate(now.getDate()-12);
  const c1='c_novak',c2='c_svoboda',c3='c_kral';
  return {
    version:2,
    settings:{company:'Novák Elektro',owner:'Petr Novák',phone:'+420 777 123 456',email:'info@novakelektro.cz'},
    contacts:[
      {id:c1,name:'Jan Novák',company:'',phone:'+420 777 222 111',email:'jan.novak@email.cz',address:'Most, Velebudická 18',note:'Vstup zezadu přes zahradu.'},
      {id:c2,name:'Martin Svoboda',company:'Svoboda Development',phone:'+420 606 334 455',email:'svoboda@firma.cz',address:'Litvínov, Studentská 42',note:'Fakturovat na firmu.'},
      {id:c3,name:'Lucie Králová',company:'',phone:'+420 608 101 202',email:'',address:'Meziboří, Okružní 7',note:''}
    ],
    jobs:[
      {id:'j1',title:'Dokončení elektroinstalace',contactId:c1,address:'Most, Velebudická 18',date:t,time:'07:30',endTime:'14:00',status:'active',price:18500,note:'Osadit zásuvky, vypínače a dokončit rozvaděč.',photos:[{name:'rozvadec_pred.jpg',at:t}],docs:[{name:'Nabídka_2026-014.pdf',type:'nabídka'}],comments:[{text:'Krabice jsou připravené, chybí rámečky.',at:t}]},
      {id:'j2',title:'Zaměření a nacenění rekonstrukce',contactId:c2,address:'Litvínov, Studentská 42',date:iso(d1),time:'15:00',endTime:'16:00',status:'planned',price:0,note:'Kompletní rekonstrukce elektro v bytě 3+1.',photos:[],docs:[],comments:[]},
      {id:'j3',title:'Zapojení kuchyňské linky',contactId:c3,address:'Meziboří, Okružní 7',date:iso(d2),time:'08:00',endTime:'11:00',status:'planned',price:6500,note:'Trouba, varná deska, myčka, kontrola okruhů.',photos:[],docs:[],comments:[]},
      {id:'j4',title:'Rozvaděč garáže',contactId:c1,address:'Most, Velebudická 18',date:iso(last),time:'08:00',endTime:'13:30',status:'done',price:12200,note:'Nový podružný rozvaděč + přívod.',photos:[{name:'garaz_hotovo.jpg',at:iso(last)},{name:'rozvadec.jpg',at:iso(last)}],docs:[{name:'Faktura_2026-087.pdf',type:'faktura'}],comments:[{text:'Přívod 5×6 mm², jistič 25 A.',at:iso(last)}]}
    ],
    tasks:[
      {id:'t1',title:'Objednat rámečky a zásuvky',date:t,status:'open',jobId:'j1',note:'Bílá řada, 12 ks.'},
      {id:'t2',title:'Zavolat Svobodovi kvůli termínu',date:iso(d1),status:'open',jobId:'j2',note:''}
    ],
    offers:[
      {id:'o1',number:'2026-015',kind:'customer',contactId:c2,customer:{name:'Martin Svoboda',company:'Svoboda Development',phone:'+420 606 334 455',email:'svoboda@firma.cz',address:'Litvínov, Studentská 42'},title:'Rekonstrukce elektroinstalace 3+1',date:t,validTo:iso(d2),items:[{name:'Elektromontážní práce',qty:24,unit:'h',price:650},{name:'Materiál – odhad',qty:1,unit:'soubor',price:21800}],note:'Cena materiálu bude upravena dle skutečné spotřeby.',convertedJobId:''},
      {id:'o2',number:'2026-016',kind:'concept',contactId:'',customer:null,title:'Standardní nabídka – montáž rozvaděče',date:t,validTo:'',items:[{name:'Práce',qty:8,unit:'h',price:650},{name:'Materiál',qty:1,unit:'soubor',price:0}],note:'Koncept určený k dalšímu doplnění.',convertedJobId:''}
    ]
  };
}
function normalizeState(s){
  const base=s&&typeof s==='object'?s:demoState();
  base.version=2;base.settings=base.settings||demoState().settings;base.contacts=base.contacts||[];base.jobs=base.jobs||[];base.tasks=base.tasks||[];base.offers=base.offers||[];
  base.offers.forEach(o=>{if(!o.kind)o.kind=o.contactId?'customer':'concept';if(o.convertedJobId==null)o.convertedJobId='';if(o.kind==='customer'&&!o.customer){const c=base.contacts.find(x=>x.id===o.contactId);if(c)o.customer={name:c.name,company:c.company,phone:c.phone,email:c.email,address:c.address};}});
  return base;
}
function load(){try{return normalizeState(JSON.parse(localStorage.getItem(KEY)))}catch(e){return demoState()}}
let state=load();
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function contact(id){return state.contacts.find(x=>x.id===id)}
function job(id){return state.jobs.find(x=>x.id===id)}
function task(id){return state.tasks.find(x=>x.id===id)}
function offer(id){return state.offers.find(x=>x.id===id)}
function totalOffer(o){return (o.items||[]).reduce((s,i)=>s+Number(i.qty||0)*Number(i.price||0),0)}
function offerCustomer(o){const c=contact(o.contactId);return o.customer&&o.customer.name?o.customer:(c?{name:c.name,company:c.company,phone:c.phone,email:c.email,address:c.address}:null)}
function nextOfferNumber(){const year=new Date().getFullYear();const nums=state.offers.map(o=>String(o.number||'')).filter(x=>x.startsWith(year+'-')).map(x=>Number(x.split('-')[1])||0);return `${year}-${String(Math.max(0,...nums)+1).padStart(3,'0')}`}

const Router={route:'dashboard',params:{},go(route,params={}){this.route=route;this.params=params;location.hash=route;render();},init(){const h=location.hash.replace('#','');if(h)this.route=h;window.addEventListener('hashchange',()=>{const r=location.hash.replace('#','');if(r&&r!==this.route){this.route=r;this.params={};render();}})}};

function topbar(title,kicker,actions=''){return `<header class="topbar"><div class="top-title"><p class="kicker">${esc(kicker)}</p><h1>${esc(title)}</h1></div><div class="top-actions">${actions}</div></header>`}
function section(title,right=''){return `<div class="section-head"><h2>${esc(title)}</h2>${right?`<span>${right}</span>`:''}</div>`}
function statusMeta(j){if(j.status==='done')return ['Hotovo','kind-green'];if(j.status==='active')return ['Probíhá','kind-blue'];return ['Naplánováno','kind-amber'];}
function jobRow(j){const c=contact(j.contactId),customerName=c?.name||j.customerSnapshot?.name||'Bez zákazníka',[st,kind]=statusMeta(j);return `<div class="row job-open ${kind}" data-id="${j.id}"><span class="row-icon">${icon('briefcase')}</span><div class="row-main"><b>${esc(j.title)}</b><small>${esc(customerName)} · ${esc(j.address||c?.address||j.customerSnapshot?.address||'Bez adresy')}</small><span class="badge">${st}</span></div><div class="row-side"><strong>${fmtShort(j.date)} ${esc(j.time||'')}</strong>${j.price?`<small>${money(j.price)}</small>`:''}</div></div>`}
function contactRow(c){const count=state.jobs.filter(j=>j.contactId===c.id).length;return `<div class="row contact-open kind-cyan" data-id="${c.id}"><span class="row-icon">${icon('person')}</span><div class="row-main"><b>${esc(c.name)}</b><small>${esc(c.company||c.address||c.phone||'Bez dalších údajů')}</small></div><div class="row-side"><strong>${count} zak.</strong><small>${esc(c.phone||'')}</small></div></div>`}
function taskRow(t){const j=job(t.jobId);return `<div class="row task-open ${t.status==='done'?'kind-green':'kind-amber'}" data-id="${t.id}"><span class="row-icon">${icon(t.status==='done'?'check':'task')}</span><div class="row-main"><b>${esc(t.title)}</b><small>${j?esc(j.title):'Samostatný úkol'}${t.note?` · ${esc(t.note)}`:''}</small><span class="badge">${t.status==='done'?'Hotovo':'Úkol'}</span></div><div class="row-side"><strong>${fmtDate(t.date)}</strong></div></div>`}
function offerRow(o){const c=offerCustomer(o),concept=o.kind==='concept';return `<div class="row offer-open ${concept?'kind-purple':'kind-blue'}" data-id="${o.id}"><span class="row-icon">${icon('offer')}</span><div class="row-main"><b>${esc(o.title)}</b><small>${concept?'Koncept bez zákazníka':esc(c?.name||'Zákazník bez kontaktu')} · Nabídka ${esc(o.number)}</small><span class="badge">${concept?'Koncept':'Připravená nabídka'}</span></div><div class="row-side"><strong>${money(totalOffer(o))}</strong><small>${fmtDate(o.date)}</small></div></div>`}

function renderDashboard(){
  const t=todayIso(),todayJobs=state.jobs.filter(j=>j.date===t&&j.status!=='done').sort((a,b)=>(a.time||'').localeCompare(b.time||'')),upcoming=state.jobs.filter(j=>j.date>=t&&j.status!=='done').sort((a,b)=>a.date.localeCompare(b.date)).slice(0,4),openTasks=state.tasks.filter(x=>x.status!=='done').sort((a,b)=>(a.date||'').localeCompare(b.date||'')).slice(0,5),active=state.jobs.filter(j=>j.status!=='done').length,done=state.jobs.filter(j=>j.status==='done').length,offers=state.offers.filter(o=>!o.convertedJobId).length,d=new Date();
  return `<div class="screen">${topbar('Moje Řemeslo','Pracovní přehled',`<button class="icon-btn" data-action="menu">${icon('menu')}</button>`)}<div class="scroll">
  <section class="hero"><span class="hero-time">${dayNames[d.getDay()]} · ${d.getDate()}. ${monthNames[d.getMonth()]}</span><h2>${todayJobs.length?`Dnes ${todayJobs.length===1?'1 zakázka':todayJobs.length<5?todayJobs.length+' zakázky':todayJobs.length+' zakázek'}`:'Dnes máte volno'}</h2><p>${todayJobs[0]?`${todayJobs[0].time} · ${esc(todayJobs[0].title)}`:'V kalendáři dnes není naplánovaná žádná práce.'}</p></section>
  <div class="stat-grid"><div class="stat blue"><b>${active}</b><span>Aktivní zakázky</span></div><div class="stat green"><b>${done}</b><span>V archivu</span></div><div class="stat amber"><b>${offers}</b><span>Rozpracované nabídky</span></div></div>
  ${section('Dnešní plán',todayJobs.length?`${todayJobs.length} položek`:'Volný den')}${todayJobs.length?`<div class="list">${todayJobs.map(jobRow).join('')}</div>`:`<div class="empty">Dnes nic naplánovaného. Přidejte zakázku přes rychlé +.</div>`}
  ${section('Nejbližší zakázky','další termíny')}${upcoming.length?`<div class="list">${upcoming.map(jobRow).join('')}</div>`:`<div class="empty">Žádné další naplánované zakázky.</div>`}
  ${section('Nejbližší úkoly',openTasks.length?`${openTasks.length} zobrazeno`:'bez úkolů')}${openTasks.length?`<div class="list">${openTasks.map(taskRow).join('')}</div>`:`<div class="empty">Nemáte žádné otevřené úkoly.</div>`}
  </div></div>`;
}

let calCursor=new Date(new Date().getFullYear(),new Date().getMonth(),1),selectedDate=todayIso();
function calendarDays(cursor){const y=cursor.getFullYear(),m=cursor.getMonth(),start=new Date(y,m,1),offset=(start.getDay()+6)%7,first=new Date(y,m,1-offset);return Array.from({length:42},(_,i)=>{const d=new Date(first);d.setDate(first.getDate()+i);return d})}
function renderCalendar(){
  const jobsDay=state.jobs.filter(j=>j.date===selectedDate).sort((a,b)=>(a.time||'').localeCompare(b.time||''));
  const cells=calendarDays(calCursor).map(d=>{const di=iso(d),items=state.jobs.filter(j=>j.date===di),out=d.getMonth()!==calCursor.getMonth();return `<button class="cal-day ${out?'out':''} ${di===selectedDate?'selected':''} ${di===todayIso()?'today':''}" data-date="${di}">${d.getDate()}<span class="dots">${items.slice(0,3).map(j=>`<i class="dot ${j.status==='done'?'green':j.status==='planned'?'amber':''}"></i>`).join('')}</span></button>`}).join('');
  return `<div class="screen">${topbar('Kalendář','Centrum pracovního dne',`<button class="icon-btn" data-action="new-job">${icon('plus')}</button>`)}<div class="scroll"><div class="segmented" style="--cols:3"><button class="active">Měsíc</button><button data-action="today">Dnes</button><button data-action="new-job">+ Zakázka</button></div><section class="calendar-shell"><div class="cal-head"><b>${monthNames[calCursor.getMonth()]} ${calCursor.getFullYear()}</b><div class="cal-nav"><button data-cal="prev">‹</button><button data-cal="next">›</button></div></div><div class="week">${['Po','Út','St','Čt','Pá','So','Ne'].map(x=>`<span>${x}</span>`).join('')}</div><div class="cal-grid">${cells}</div></section>${section(fmtDate(selectedDate),jobsDay.length?`${jobsDay.length} zakázek`:'bez zakázek')}${jobsDay.length?`<div class="list">${jobsDay.map(jobRow).join('')}</div>`:`<div class="empty">Na tento den není nic naplánováno.</div>`}</div></div>`;
}

let jobsTab='active';
function renderJobs(){const list=state.jobs.filter(j=>jobsTab==='archive'?j.status==='done':j.status!=='done').sort((a,b)=>jobsTab==='archive'?b.date.localeCompare(a.date):a.date.localeCompare(b.date));return `<div class="screen">${topbar(jobsTab==='archive'?'Archiv prací':'Zakázky',jobsTab==='archive'?'Historie dokončené práce':'Aktivní a plánované práce',`<button class="icon-btn" data-action="new-job">${icon('plus')}</button>`)}<div class="scroll"><div class="segmented"><button data-jobtab="active" class="${jobsTab==='active'?'active':''}">Aktivní</button><button data-jobtab="archive" class="${jobsTab==='archive'?'active':''}">Archiv</button></div><div class="search">${icon('search')}<input id="jobSearch" placeholder="Hledat zakázku, zákazníka, adresu…"></div><div id="jobsList">${list.length?`<div class="list">${list.map(jobRow).join('')}</div>`:`<div class="empty">${jobsTab==='archive'?'Archiv je zatím prázdný.':'Nemáte žádné aktivní zakázky.'}</div>`}</div></div></div>`}
function renderTasks(){const open=state.tasks.filter(t=>t.status!=='done').sort((a,b)=>(a.date||'').localeCompare(b.date||'')),done=state.tasks.filter(t=>t.status==='done').sort((a,b)=>(b.date||'').localeCompare(a.date||''));return `<div class="screen">${topbar('Úkoly','Co je potřeba udělat',`<button class="icon-btn" data-action="new-task">${icon('plus')}</button>`)}<div class="scroll">${section('Otevřené',open.length?`${open.length}`:'0')}${open.length?`<div class="list">${open.map(taskRow).join('')}</div>`:`<div class="empty">Žádné otevřené úkoly.</div>`}${done.length?`${section('Hotové',done.length)}<div class="list">${done.map(taskRow).join('')}</div>`:''}<button class="fab-inline" data-action="new-task">+ Nový úkol</button></div></div>`}
function renderContacts(){return `<div class="screen">${topbar('Kontakty','Zákazníci a historie',`<button class="icon-btn" data-action="new-contact">${icon('plus')}</button>`)}<div class="scroll"><div class="search">${icon('search')}<input id="contactSearch" placeholder="Hledat jméno, firmu, telefon…"></div><div id="contactsList">${state.contacts.length?`<div class="list">${state.contacts.slice().sort((a,b)=>a.name.localeCompare(b.name,'cs')).map(contactRow).join('')}</div>`:`<div class="empty">Žádné kontakty.</div>`}</div></div></div>`}
function renderOffers(){const list=state.offers.filter(o=>!o.convertedJobId).sort((a,b)=>(b.date||'').localeCompare(a.date||''));return `<div class="screen">${topbar('Nabídky','Rozpracované cenové nabídky',`<button class="icon-btn" data-action="new-offer">${icon('plus')}</button>`)}<div class="scroll"><div class="offer-intro"><b>Nabídky, ze kterých ještě nevznikla zakázka</b><span>Koncept můžete kdykoli doplnit. Hotovou nabídku lze vygenerovat do PDF a poslat zákazníkovi.</span></div>${list.length?`<div class="list">${list.map(offerRow).join('')}</div>`:`<div class="empty">Žádné rozpracované nabídky. Nabídka po vytvoření zakázky z tohoto přehledu zmizí.</div>`}<button class="fab-inline" data-action="new-offer">+ Nová cenová nabídka</button></div></div>`}

function render(){
  let html='';if(Router.route==='dashboard')html=renderDashboard();else if(Router.route==='calendar')html=renderCalendar();else if(Router.route==='tasks')html=renderTasks();else if(Router.route==='jobs')html=renderJobs();else if(Router.route==='contacts')html=renderContacts();else if(Router.route==='offers')html=renderOffers();else html=renderDashboard();
  $('#app-content').innerHTML=html;hydrateIcons();$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route===Router.route));bind();
}
function bind(){
  $$('[data-route]').forEach(b=>b.onclick=()=>Router.go(b.dataset.route));
  $$('[data-action]').forEach(b=>b.onclick=e=>{e.stopPropagation();action(b.dataset.action,b.dataset.id)});
  $$('.job-open').forEach(x=>x.onclick=()=>openJob(x.dataset.id));$$('.contact-open').forEach(x=>x.onclick=()=>openContact(x.dataset.id));$$('.task-open').forEach(x=>x.onclick=()=>openTask(x.dataset.id));$$('.offer-open').forEach(x=>x.onclick=()=>openOffer(x.dataset.id));
  $$('[data-jobtab]').forEach(b=>b.onclick=()=>{jobsTab=b.dataset.jobtab;render()});$$('[data-cal]').forEach(b=>b.onclick=()=>{calCursor.setMonth(calCursor.getMonth()+(b.dataset.cal==='next'?1:-1));render()});$$('.cal-day').forEach(b=>b.onclick=()=>{selectedDate=b.dataset.date;render()});
  const js=$('#jobSearch');if(js)js.oninput=()=>filterJobs(js.value);const cs=$('#contactSearch');if(cs)cs.oninput=()=>filterContacts(cs.value);
}
function action(a){if(a==='new-job')openJobForm();if(a==='new-task')openTaskForm();if(a==='new-contact')openContactForm();if(a==='new-offer')openOfferForm();if(a==='today'){selectedDate=todayIso();calCursor=new Date();render()}if(a==='menu')openMenu();}
function filterJobs(q){q=q.toLowerCase().trim();const list=state.jobs.filter(j=>(jobsTab==='archive'?j.status==='done':j.status!=='done')).filter(j=>{const c=contact(j.contactId);return [j.title,j.address,j.note,c?.name,c?.phone,j.customerSnapshot?.name,j.customerSnapshot?.phone].join(' ').toLowerCase().includes(q)});$('#jobsList').innerHTML=list.length?`<div class="list">${list.map(jobRow).join('')}</div>`:'<div class="empty">Nic nenalezeno.</div>';$$('.job-open').forEach(x=>x.onclick=()=>openJob(x.dataset.id));}
function filterContacts(q){q=q.toLowerCase().trim();const list=state.contacts.filter(c=>[c.name,c.company,c.phone,c.email,c.address].join(' ').toLowerCase().includes(q));$('#contactsList').innerHTML=list.length?`<div class="list">${list.map(contactRow).join('')}</div>`:'<div class="empty">Nic nenalezeno.</div>';$$('.contact-open').forEach(x=>x.onclick=()=>openContact(x.dataset.id));}

function showModal(body){$('#modal-root').innerHTML=`<div class="modal-wrap"><div class="modal">${body}</div></div>`;$('.modal-wrap').onclick=e=>{if(e.target.classList.contains('modal-wrap'))closeModal()};$$('[data-close]').forEach(b=>b.onclick=closeModal)}
function closeModal(){$('#modal-root').innerHTML=''}
function modalHead(kicker,title){return `<div class="modal-head"><div><p>${esc(kicker)}</p><h2>${esc(title)}</h2></div><button class="close-btn" data-close>×</button></div>`}
function contactOptions(selected='',emptyLabel='Bez kontaktu'){return `<option value="">${esc(emptyLabel)}</option>${state.contacts.map(c=>`<option value="${c.id}" ${c.id===selected?'selected':''}>${esc(c.name)}${c.company?` · ${esc(c.company)}`:''}</option>`).join('')}`}
function jobOptions(selected=''){return `<option value="">Bez vazby na zakázku</option>${state.jobs.filter(j=>j.status!=='done').map(j=>`<option value="${j.id}" ${j.id===selected?'selected':''}>${esc(j.title)}</option>`).join('')}`}

function openJobForm(existing=null,onSaved=null){
  const isExisting=!!existing?.id,j=existing||{title:'',contactId:'',address:'',date:selectedDate||todayIso(),time:'08:00',endTime:'',status:'planned',price:'',note:'',photos:[],docs:[],comments:[]};
  showModal(`${modalHead(isExisting?'Upravit zakázku':'Nová zakázka',isExisting?'Detail a termín':'Zapište práci rovnou do kalendáře')}<form id="jobForm" class="form-grid"><div class="field"><label>Název práce</label><input name="title" required value="${esc(j.title)}" placeholder="Např. Montáž rozvaděče"></div><div class="field"><label>Zákazník</label><select name="contactId">${contactOptions(j.contactId)}</select></div><div class="field"><label>Adresa realizace</label><input name="address" value="${esc(j.address||'')}" placeholder="Město, ulice"></div><div class="two"><div class="field"><label>Datum</label><input type="date" name="date" required value="${j.date||todayIso()}"></div><div class="field"><label>Stav</label><select name="status"><option value="planned" ${j.status==='planned'?'selected':''}>Naplánováno</option><option value="active" ${j.status==='active'?'selected':''}>Probíhá</option><option value="done" ${j.status==='done'?'selected':''}>Hotovo</option></select></div></div><div class="two"><div class="field"><label>Od</label><input type="time" name="time" value="${j.time||''}"></div><div class="field"><label>Do</label><input type="time" name="endTime" value="${j.endTime||''}"></div></div><div class="field"><label>Dohodnutá cena</label><input type="number" step="1" name="price" value="${j.price||''}" placeholder="0"></div><div class="field"><label>Poznámka</label><textarea name="note">${esc(j.note||'')}</textarea></div><button class="primary">${isExisting?'Uložit zakázku':'Vytvořit zakázku'}</button></form>`);
  $('#jobForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target),obj={title:fd.get('title'),contactId:fd.get('contactId'),address:fd.get('address'),date:fd.get('date'),time:fd.get('time'),endTime:fd.get('endTime'),status:fd.get('status'),price:Number(fd.get('price')||0),note:fd.get('note')};let saved;if(isExisting){Object.assign(j,obj);saved=j}else{saved={...j,...obj,id:uid('j'),photos:j.photos||[],docs:j.docs||[],comments:j.comments||[]};state.jobs.push(saved)}save();closeModal();if(onSaved)onSaved(saved);else render();};
}
function openJob(id){const j=job(id),c=contact(j.contactId),customerName=c?.name||j.customerSnapshot?.name||'Bez kontaktu',[st]=statusMeta(j);showModal(`${modalHead(st,j.title)}<div class="detail-meta"><div class="meta-box"><span>Zákazník</span><b>${esc(customerName)}</b></div><div class="meta-box"><span>Termín</span><b>${fmtDate(j.date)} ${esc(j.time||'')}</b></div></div>${j.address?`<div class="note">📍 ${esc(j.address)}</div>`:''}${j.note?`${section('Popis práce')}<div class="note">${esc(j.note)}</div>`:''}${section('Poznámky')}<div id="comments">${(j.comments||[]).map(x=>`<div class="doc-row"><span>${esc(x.text)}<br><small>${fmtDate(x.at)}</small></span></div>`).join('')||'<div class="empty">Bez poznámek.</div>'}</div><button class="secondary" id="addComment">+ Přidat poznámku</button>${section('Fotky',`${(j.photos||[]).length}`)}${(j.photos||[]).map(x=>`<div class="doc-row"><span>${icon('camera',16)} ${esc(x.name)}</span><small>${fmtDate(x.at)}</small></div>`).join('')||'<div class="empty">Bez fotek.</div>'}<button class="secondary" id="addPhoto">+ Přidat fotky</button>${section('Dokumenty',`${(j.docs||[]).length}`)}${(j.docs||[]).map(x=>`<div class="doc-row"><span>${icon('file',16)} ${esc(x.name)}</span><span class="tag">${esc(x.type||'soubor')}</span></div>`).join('')||'<div class="empty">Bez dokumentů.</div>'}<button class="secondary" id="addDoc">+ Přidat dokument</button><button class="primary" id="editJob">Upravit zakázku</button>${j.status!=='done'?`<button class="secondary" id="finishJob">Označit jako hotovou a archivovat</button>`:''}`);$('#editJob').onclick=()=>openJobForm(j);if($('#finishJob'))$('#finishJob').onclick=()=>{j.status='done';save();closeModal();render()};$('#addComment').onclick=()=>{const text=prompt('Poznámka k zakázce:');if(text){j.comments=j.comments||[];j.comments.push({text,at:todayIso()});save();openJob(id)}};$('#addPhoto').onclick=()=>openFilePicker(j,'photo');$('#addDoc').onclick=()=>openFilePicker(j,'doc');}
function openFilePicker(j,type){const inp=document.createElement('input');inp.type='file';if(type==='photo')inp.accept='image/*';inp.multiple=true;inp.onchange=()=>{const arr=[...inp.files];if(type==='photo'){j.photos=j.photos||[];arr.forEach(f=>j.photos.push({name:f.name,at:todayIso()}))}else{j.docs=j.docs||[];arr.forEach(f=>j.docs.push({name:f.name,type:f.type?.includes('pdf')?'PDF':'soubor'}))}save();openJob(j.id)};inp.click()}

function openTaskForm(existing=null){const t=existing||{title:'',date:todayIso(),status:'open',jobId:'',note:''};showModal(`${modalHead(existing?'Upravit úkol':'Nový úkol','Jednoduchý pracovní úkol')}<form id="taskForm" class="form-grid"><div class="field"><label>Úkol</label><input required name="title" value="${esc(t.title)}" placeholder="Co je potřeba udělat?"></div><div class="two"><div class="field"><label>Termín</label><input type="date" name="date" value="${t.date||todayIso()}"></div><div class="field"><label>Stav</label><select name="status"><option value="open" ${t.status!=='done'?'selected':''}>Otevřený</option><option value="done" ${t.status==='done'?'selected':''}>Hotový</option></select></div></div><div class="field"><label>Zakázka</label><select name="jobId">${jobOptions(t.jobId)}</select></div><div class="field"><label>Poznámka</label><textarea name="note">${esc(t.note||'')}</textarea></div><button class="primary">${existing?'Uložit úkol':'Přidat úkol'}</button></form>`);$('#taskForm').onsubmit=e=>{e.preventDefault();const obj=Object.fromEntries(new FormData(e.target).entries());if(existing)Object.assign(existing,obj);else state.tasks.push({...obj,id:uid('t')});save();closeModal();Router.go('tasks')}}
function openTask(id){const t=task(id),j=job(t.jobId);showModal(`${modalHead(t.status==='done'?'Hotový úkol':'Úkol',t.title)}<div class="detail-meta"><div class="meta-box"><span>Termín</span><b>${fmtDate(t.date)}</b></div><div class="meta-box"><span>Zakázka</span><b>${esc(j?.title||'Bez vazby')}</b></div></div>${t.note?`<div class="note">${esc(t.note)}</div>`:''}${t.status!=='done'?`<button class="primary" id="finishTask">Označit jako hotový</button>`:''}<button class="secondary" id="editTask">Upravit</button><button class="secondary danger-btn" id="deleteTask">Odstranit</button>`);if($('#finishTask'))$('#finishTask').onclick=()=>{t.status='done';save();closeModal();render()};$('#editTask').onclick=()=>openTaskForm(t);$('#deleteTask').onclick=()=>{if(confirm('Odstranit tento úkol?')){state.tasks=state.tasks.filter(x=>x.id!==id);save();closeModal();render()}}}

function openContactForm(existing=null,preset=null,onSave=null){const c=existing||preset||{name:'',company:'',phone:'',email:'',address:'',note:''};showModal(`${modalHead(existing?'Upravit kontakt':'Nový kontakt','Zákazník a jeho historie')}<form id="contactForm" class="form-grid"><div class="field"><label>Jméno / název</label><input required name="name" value="${esc(c.name||'')}"></div><div class="field"><label>Firma</label><input name="company" value="${esc(c.company||'')}"></div><div class="two"><div class="field"><label>Telefon</label><input name="phone" value="${esc(c.phone||'')}"></div><div class="field"><label>E-mail</label><input type="email" name="email" value="${esc(c.email||'')}"></div></div><div class="field"><label>Adresa</label><input name="address" value="${esc(c.address||'')}"></div><div class="field"><label>Poznámka</label><textarea name="note">${esc(c.note||'')}</textarea></div><button class="primary">${existing?'Uložit kontakt':'Přidat kontakt'}</button></form>`);$('#contactForm').onsubmit=e=>{e.preventDefault();const obj=Object.fromEntries(new FormData(e.target).entries());let saved;if(existing){Object.assign(existing,obj);saved=existing}else{saved={...obj,id:uid('c')};state.contacts.push(saved)}save();closeModal();if(onSave)onSave(saved);else render();}}
function openContact(id){const c=contact(id),jobs=state.jobs.filter(j=>j.contactId===id).sort((a,b)=>b.date.localeCompare(a.date));showModal(`${modalHead('Kontakt',c.name)}<div class="detail-meta"><div class="meta-box"><span>Telefon</span><b>${esc(c.phone||'—')}</b></div><div class="meta-box"><span>E-mail</span><b>${esc(c.email||'—')}</b></div></div>${c.address?`<div class="note">📍 ${esc(c.address)}</div>`:''}${c.note?`${section('Poznámka')}<div class="note">${esc(c.note)}</div>`:''}${section('Historie zakázek',`${jobs.length} celkem`)}${jobs.length?`<div class="list">${jobs.map(jobRow).join('')}</div>`:`<div class="empty">Bez zakázek.</div>`}<button class="primary" id="contactNewJob">+ Nová zakázka pro zákazníka</button><button class="secondary" id="editContact">Upravit kontakt</button>`);$$('.job-open').forEach(x=>x.onclick=()=>openJob(x.dataset.id));$('#editContact').onclick=()=>openContactForm(c);$('#contactNewJob').onclick=()=>openJobForm({title:'',contactId:c.id,address:c.address,date:todayIso(),time:'08:00',endTime:'',status:'planned',price:0,note:'',photos:[],docs:[],comments:[]})}

function offerCustomerFields(c={}){return `<div id="offerCustomerFields" class="form-grid"><div class="field"><label>Vybrat z kontaktů (volitelné)</label><select name="contactId" id="offerContactSelect">${contactOptions(c.contactId||'','Nový / neuložený zákazník')}</select></div><div class="field"><label>Jméno / název zákazníka</label><input name="customer_name" value="${esc(c.name||'')}" placeholder="Např. Jan Novák"></div><div class="field"><label>Firma</label><input name="customer_company" value="${esc(c.company||'')}"></div><div class="two"><div class="field"><label>Telefon</label><input name="customer_phone" value="${esc(c.phone||'')}"></div><div class="field"><label>E-mail</label><input type="email" name="customer_email" value="${esc(c.email||'')}"></div></div><div class="field"><label>Adresa zákazníka</label><input name="customer_address" value="${esc(c.address||'')}"></div></div>`}
function itemFields(i){return `<div class="offer-item form-grid"><div class="offer-item-head"><span>Položka nabídky</span><button type="button" class="item-remove" aria-label="Odstranit">×</button></div><div class="field"><label>Položka</label><input name="item_name" value="${esc(i.name||'')}"></div><div class="two"><div class="field"><label>Množství</label><input type="number" step="0.01" name="item_qty" value="${i.qty??1}"></div><div class="field"><label>Jednotka</label><input name="item_unit" value="${esc(i.unit||'ks')}"></div></div><div class="field"><label>Cena / jednotku</label><input type="number" step="0.01" name="item_price" value="${i.price??0}"></div></div>`}
function readOfferForm(form){const fd=new FormData(form),kind=fd.get('kind')||'concept',obj={number:fd.get('number'),kind,contactId:kind==='customer'?fd.get('contactId'):'',customer:null,title:fd.get('title'),date:fd.get('date'),validTo:fd.get('validTo'),note:fd.get('note'),items:[],convertedJobId:''};if(kind==='customer')obj.customer={name:fd.get('customer_name')||'',company:fd.get('customer_company')||'',phone:fd.get('customer_phone')||'',email:fd.get('customer_email')||'',address:fd.get('customer_address')||''};const names=fd.getAll('item_name'),qty=fd.getAll('item_qty'),unit=fd.getAll('item_unit'),price=fd.getAll('item_price');names.forEach((n,i)=>{if(String(n).trim())obj.items.push({name:n,qty:Number(qty[i]||0),unit:unit[i],price:Number(price[i]||0)})});return obj;}
function commitOffer(obj,existing=null){let saved;if(existing){const converted=existing.convertedJobId||'';Object.assign(existing,obj,{convertedJobId:converted});saved=existing}else{saved={...obj,id:uid('o')};state.offers.push(saved)}save();closeModal();Router.go('offers');setTimeout(()=>openOffer(saved.id),0);}
function askAddCustomerToContacts(obj,existing=null){showModal(`${modalHead('Nový zákazník','Přidat zákazníka také do kontaktů?')}<div class="note">Nabídka je určená pro <b>${esc(obj.customer?.name||'nového zákazníka')}</b>, ale tento zákazník zatím není uložený v kontaktech.</div><button class="primary" id="offerAddContact">Ano, přidat do kontaktů</button><button class="secondary" id="offerWithoutContact">Ne, vytvořit jen nabídku</button><button class="secondary" id="offerBackEdit">Zpět k úpravě nabídky</button>`);$('#offerAddContact').onclick=()=>openContactForm(null,{...obj.customer,note:''},c=>{obj.contactId=c.id;obj.customer={name:c.name,company:c.company,phone:c.phone,email:c.email,address:c.address};commitOffer(obj,existing)});$('#offerWithoutContact').onclick=()=>commitOffer(obj,existing);$('#offerBackEdit').onclick=()=>openOfferForm(existing,obj);}
function openOfferForm(existing=null,draft=null){
  const base=draft||existing||{number:nextOfferNumber(),kind:'concept',contactId:'',customer:null,title:'Cenová nabídka',date:todayIso(),validTo:'',items:[{name:'Práce',qty:1,unit:'h',price:0}],note:'',convertedJobId:''};const c=base.customer||contact(base.contactId)||{};
  showModal(`${modalHead(existing?'Upravit nabídku':'Nová nabídka',base.kind==='concept'?'Koncept lze později doplnit':'Nabídka pro konkrétního zákazníka')}<form id="offerForm" class="form-grid"><input type="hidden" name="kind" value="${esc(base.kind||'concept')}"><div class="segmented offer-kind" style="--cols:2"><button type="button" data-offerkind="concept" class="${base.kind==='concept'?'active':''}">Koncept</button><button type="button" data-offerkind="customer" class="${base.kind==='customer'?'active':''}">Pro zákazníka</button></div><div id="offerModeHint" class="form-hint">${base.kind==='concept'?'Bez konkrétního adresáta. Vše zůstává plně editovatelné.':'V PDF bude viditelná hlavička zákazníka.'}</div><div id="customerArea">${base.kind==='customer'?offerCustomerFields({...c,contactId:base.contactId}):''}</div><div class="two"><div class="field"><label>Číslo nabídky</label><input name="number" value="${esc(base.number)}"></div><div class="field"><label>Datum</label><input type="date" name="date" value="${base.date||todayIso()}"></div></div><div class="field"><label>Název nabídky</label><input required name="title" value="${esc(base.title)}" placeholder="Např. Elektroinstalace rodinného domu"></div><div class="field"><label>Platnost do</label><input type="date" name="validTo" value="${base.validTo||''}"></div>${section('Položky')}<div id="offerItems">${(base.items||[]).map(itemFields).join('')}</div><button type="button" class="secondary" id="addOfferItem">+ Přidat položku</button><div class="field"><label>Poznámka</label><textarea name="note">${esc(base.note||'')}</textarea></div><button class="primary">${existing?'Uložit změny':'Vytvořit nabídku'}</button></form>`);
  function bindCustomerSelect(){const s=$('#offerContactSelect');if(!s)return;s.onchange=()=>{const c=contact(s.value);if(!c)return;const f=$('#offerForm');f.elements.customer_name.value=c.name||'';f.elements.customer_company.value=c.company||'';f.elements.customer_phone.value=c.phone||'';f.elements.customer_email.value=c.email||'';f.elements.customer_address.value=c.address||'';};}
  $$('[data-offerkind]').forEach(b=>b.onclick=()=>{const kind=b.dataset.offerkind;$('#offerForm').elements.kind.value=kind;$$('[data-offerkind]').forEach(x=>x.classList.toggle('active',x===b));$('#customerArea').innerHTML=kind==='customer'?offerCustomerFields({}):'';$('#offerModeHint').textContent=kind==='concept'?'Bez konkrétního adresáta. Vše zůstává plně editovatelné.':'V PDF bude viditelná hlavička zákazníka.';bindCustomerSelect();});
  $('#addOfferItem').onclick=()=>{$('#offerItems').insertAdjacentHTML('beforeend',itemFields({name:'',qty:1,unit:'ks',price:0}));bindOfferItemRemovers();};
  function bindOfferItemRemovers(){$$('.item-remove').forEach(b=>b.onclick=()=>{if($$('.offer-item').length>1)b.closest('.offer-item').remove();});}
  bindOfferItemRemovers();bindCustomerSelect();
  $('#offerForm').onsubmit=e=>{e.preventDefault();const obj=readOfferForm(e.target);if(obj.kind==='customer'&&!obj.customer?.name.trim()){alert('Vyplňte jméno nebo název zákazníka.');return}if(!obj.items.length){alert('Přidejte alespoň jednu položku nabídky.');return}if(obj.kind==='customer'&&!obj.contactId)askAddCustomerToContacts(obj,existing);else commitOffer(obj,existing);};
}
function offerPreviewHtml(o){const c=offerCustomer(o),concept=o.kind==='concept'||!c;return `<div class="offer-preview"><div class="offer-preview-head"><span>${esc(state.settings.company||'Moje Řemeslo')}</span><b>CENOVÁ NABÍDKA</b></div><div class="offer-preview-title"><small>Nabídka ${esc(o.number)}</small><h3>${esc(o.title)}</h3>${concept?'<span class="concept-label">KONCEPT</span>':`<p>Pro: <b>${esc(c.name||'')}</b>${c.company?` · ${esc(c.company)}`:''}</p>`}</div><div class="offer-preview-meta"><span>Vystaveno <b>${fmtDate(o.date)}</b></span><span>Platnost <b>${fmtDate(o.validTo)}</b></span></div>${o.items.map(i=>`<div class="offer-preview-row"><span><b>${esc(i.name)}</b><small>${Number(i.qty||0).toLocaleString('cs-CZ')} ${esc(i.unit)} × ${money(i.price)}</small></span><strong>${money(Number(i.qty||0)*Number(i.price||0))}</strong></div>`).join('')}<div class="offer-preview-total"><span>CELKEM</span><b>${money(totalOffer(o))}</b></div>${o.note?`<div class="offer-preview-note">${esc(o.note)}</div>`:''}</div>`}
function openOffer(id){
  const o=offer(id);if(!o)return;showModal(`${modalHead(o.kind==='concept'?'Koncept nabídky':`Nabídka pro ${offerCustomer(o)?.name||'zákazníka'}`,o.title)}${offerPreviewHtml(o)}<div class="offer-actions"><button class="primary" id="downloadOffer">${icon('download',17)} Vygenerovat PDF</button><button class="secondary" id="shareOffer">${icon('share',17)} Sdílet PDF</button><button class="secondary" id="offerToJob">Vytvořit z nabídky zakázku</button><button class="secondary" id="editOffer">Upravit nabídku</button><button class="secondary danger-btn" id="deleteOffer">Odstranit nabídku</button></div>`);
  $('#downloadOffer').onclick=()=>{try{OfferPdf.download(o,state)}catch(e){alert('PDF se nepodařilo vytvořit: '+e.message)}};
  $('#shareOffer').onclick=async()=>{try{await OfferPdf.share(o,state)}catch(e){if(e.name!=='AbortError')alert('Sdílení se nepodařilo: '+e.message)}};
  $('#editOffer').onclick=()=>openOfferForm(o);
  $('#deleteOffer').onclick=()=>{if(confirm(`Odstranit nabídku ${o.number}?`)){state.offers=state.offers.filter(x=>x.id!==id);save();closeModal();render()}};
  $('#offerToJob').onclick=()=>{const c=offerCustomer(o);openJobForm({title:o.title,contactId:o.contactId||'',customerSnapshot:c?{...c}:null,address:c?.address||'',date:todayIso(),time:'08:00',endTime:'',status:'planned',price:totalOffer(o),note:o.note,photos:[],docs:[{name:OfferPdf.fileName(o),type:'nabídka'}],comments:[]},j=>{o.convertedJobId=j.id;save();Router.go('jobs')})};
}

function openMenu(){showModal(`${modalHead('Aplikace','Moje Řemeslo')}<div class="list"><div class="row"><span class="row-icon kind-blue">${icon('briefcase')}</span><div class="row-main"><b>${esc(state.settings.company)}</b><small>${esc(state.settings.owner)} · lokální profil</small></div></div><div class="row" id="exportData"><span class="row-icon kind-green">${icon('file')}</span><div class="row-main"><b>Exportovat data</b><small>Stáhnout JSON zálohu aplikace</small></div></div><div class="row" id="resetDemo"><span class="row-icon kind-danger">${icon('trash')}</span><div class="row-main"><b>Obnovit demo data</b><small>Smaže lokální změny a vrátí ukázkový obsah</small></div></div></div><p style="color:var(--muted);font-size:9px;margin-top:14px">Moje Řemeslo · pracovní prototyp v2</p>`);$('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='moje-remeslo-zaloha.json';a.click();URL.revokeObjectURL(a.href)};$('#resetDemo').onclick=()=>{if(confirm('Vrátit ukázková data?')){state=demoState();save();closeModal();render()}}}

function openQuick(){const bd=$('#backdrop'),q=$('#quick-add');bd.hidden=false;q.hidden=false;q.innerHTML=`<div class="quick-panel"><div class="quick-title">Rychlé přidání</div><div class="quick-grid"><button class="quick-action kind-blue" data-q="job"><b>Zakázka</b><small>Termín rovnou do kalendáře</small></button><button class="quick-action kind-amber" data-q="task"><b>Úkol</b><small>Co je potřeba udělat</small></button><button class="quick-action kind-cyan" data-q="contact"><b>Kontakt</b><small>Nový zákazník</small></button><button class="quick-action kind-purple" data-q="offer"><b>Nabídka</b><small>Rychlé nacenění + PDF</small></button><button class="quick-action kind-amber" data-q="calendar"><b>Kalendář</b><small>Přejít na dnešní den</small></button></div></div>`;$$('[data-q]',q).forEach(b=>b.onclick=()=>{closeQuick();if(b.dataset.q==='job')openJobForm();if(b.dataset.q==='task')openTaskForm();if(b.dataset.q==='contact')openContactForm();if(b.dataset.q==='offer')openOfferForm();if(b.dataset.q==='calendar'){selectedDate=todayIso();calCursor=new Date();Router.go('calendar')}})}
function closeQuick(){$('#backdrop').hidden=true;$('#quick-add').hidden=true;$('#quick-add').innerHTML=''}
$('#quickAddBtn').onclick=()=>$('#quick-add').hidden?openQuick():closeQuick();$('#backdrop').onclick=closeQuick;

Router.init();render();hydrateIcons();
if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
